# Generated by Django 5.2.8 on 2025-11-17 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_rename_item_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
