# Generated by Django 5.2.8 on 2026-02-08 19:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_item_created_at_item_is_available_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_name',
            field=models.CharField(db_index=True, max_length=30),
        ),
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['item_name', 'item_price'], name='foodapp_ite_item_na_e04ef6_idx'),
        ),
    ]
