# Generated by Django 5.2.8 on 2026-02-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0012_alter_item_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.ImageField(blank=True, default='default/default_dish.png', upload_to='item_images/'),
        ),
    ]
