# Generated by Django 5.2.8 on 2025-11-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default_profile_pic.png', null=True, upload_to='profile_images/'),
        ),
    ]
